version: "3.5"

secrets:
  nginx_site_conf:
    file: ./docker/nginx/site.conf
  php_ini:
    file: ./docker/php/php.ini

networks:
  net: {}

services:
  web:
    image: nginx:latest
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./frontend/web:/app/frontend/web:ro
      - ./backend/web:/app/backend/web:ro
    secrets:
      - source: nginx_site_conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    networks:
      net:
        aliases:
          - ${APP_FRONTEND_HOST}
          #- ${APP_BACKEND_HOST}

  # https://docs.docker.com/samples/library/php/
  fpm:
    build:
      context: .
      dockerfile: ./docker/php/fpm/Dockerfile
    volumes: &php_volumes
      - ./runtime/.composer:/root/.composer
      - .:/app
    secrets: &php_secrets
      - source: php_ini
        target: /usr/local/etc/php/php.ini
    environment: &php_environment
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on: &php_depends_on
      - mysql
      - rabbitmq
    networks: &php_networks
      net: {}

  # https://docs.docker.com/samples/library/mysql/
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
      - ./runtime/mysql:/var/lib/mysql
    command:
      #- --sql-mode=
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      net: {}

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - ${RABBITMQ_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./runtime/rabbitmq:/var/lib/rabbitmq
    networks: &php_networks
      net: {}